name: jetson-containers
services:
    sensors:
        build:
            context: ./sensors
            dockerfile: Dockerfile
        network_mode: host
        volumes: 
            - /home/altaga/workspace/sensors:/home/altaga
        devices:
            - /dev/ttyTHS1
        working_dir: /home/altaga
        container_name: sensors-container
        image: altaga/sensors:latest
    opencv:
        build:
            context: ./opencv
            dockerfile: Dockerfile
        runtime: nvidia
        shm_size: 8g
        network_mode: host
        volumes:
            - /tmp/argus_socket:/tmp/argus_socket
            - /etc/enctune.conf:/etc/enctune.conf
            - /etc/nv_tegra_release:/etc/nv_tegra_release
            - /tmp/nv_jetson_model:/tmp/nv_jetson_model
            - /var/run/dbus:/var/run/dbus
            - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/altaga/jetson-containers/data:/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /run/user/1000/pulse:/run/user/1000/pulse
            - /home/altaga/workspace/opencv:/home/altaga
        devices:
            - /dev/snd
            - /dev/bus/usb
            - /dev/i2c-0
            - /dev/i2c-1
            - /dev/i2c-2
            - /dev/i2c-4
            - /dev/i2c-5
            - /dev/i2c-7
            - /dev/i2c-9
            - /dev/video0
        environment:
            - PULSE_SERVER=unix:/run/user/1000/pulse/native
        container_name: opencv-container
        image: altaga/opencv:latest
        working_dir: /home/altaga